=== jmthompson2015/rivalry/trunk/core/src/main/resources/DataCollector.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://core.rivalry.org/datacollector" xmlns:altova="http://www.altova.com/xml-schema-extensions" targetNamespace="http://core.rivalry.org/datacollector">
    <element name="DCSpec">
        <annotation>
            <documentation>Data collector specification</documentation>
        </annotation>
        <complexType>
            <sequence>
                <element name="url" type="string"/>
                <element name="selector" type="tns:DCSelector" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="DCSelector">
        <annotation>
            <documentation>HTML DOM selector</documentation>
        </annotation>
        <sequence>
            <element name="type" type="tns:SelectorType">
                <annotation>
                    <documentation>Selector type as supported by Selenium Web Driver By class.</documentation>
                </annotation>
            </element>
            <element name="value" type="string"/>
            <element name="selector" type="tns:DCSelector" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <simpleType name="SelectorType">
        <restriction base="string"/>
    </simpleType>
</schema>

=== jmthompson2015/rivalry/trunk/example/src/main/resources/org/rivalry/example/dogbreed/DataCollectorDogTime.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector http://rivalry.googlecode.com/svn/trunk/core/src/main/resources/DataCollector.xsd">
    <url>http://dogtime.com/dog-breeds/$1</url>
    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//*[contains(text(), 'See All Characteristic Ratings')]</value>
        </selector>
    </selector>
    <selector>
        <type>CLASS_NAME</type>
        <value>characteristics</value>
        <selector>
            <type>TAG_NAME</type>
            <value>h3</value>
        </selector>
        <selector>
            <type>CLASS_NAME</type>
            <value>five-star-ratings</value>
        </selector>
    </selector>
</tns:DCSpec>

=== jmthompson2015/rivalry/example/src/main/resources/org/rivalry/example/bestplace/DataCollectorBestPlaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector http://rivalry.googlecode.com/svn/trunk/core/src/main/resources/DataCollector.xsd">
    <url>http://www.bestplaces.net/city/$1</url>
    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Climate']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgClimate</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a|//td/font/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>(//td/a|//td/font/a)/ancestor::td/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Climate</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Cost of Living']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgCostOfLiving</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Cost of Living</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Crime']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgCrime</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Crime</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Economy']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgEconomy</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Economy</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Education']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgEducation</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Education</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Health']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgHealth</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Health</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Housing']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgHousing</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Housing</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='People']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgPeople</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>People</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Religion']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgReligion</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Religion</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Transportation']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgTransportation</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Transportation</value>
        </selector>
    </selector>

    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Voting']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgVoting</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Voting</value>
        </selector>
    </selector>
</tns:DCSpec>

=== jmthompson2015/rivalry/example/src/main/resources/org/rivalry/example/skilldemand/DataCollectorDice.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector http://rivalry.googlecode.com/svn/trunk/core/src/main/resources/DataCollector.xsd">
    <url>http://seeker.dice.com/jobsearch/servlet/JobSearch?op=300&amp;QUICK=1&amp;FREE_TEXT=$1&amp;Ntx=mode+matchall</url>
    <selector>
        <type>ID</type>
        <value>searchResHD</value>
        <selector>
            <type>LITERAL</type>
            <value>Count</value>
        </selector>
        <selector>
            <type>TAG_NAME</type>
            <value>h2</value>
        </selector>
    </selector>
</tns:DCSpec>

=== jmthompson2015/rivalry/trunk/example/src/main/resources/org/rivalry/example/boardgame/DataCollectorBoardGameGeek.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector http://rivalry.googlecode.com/svn/trunk/core/src/main/resources/DataCollector.xsd">
    <url>http://dogtime.com/dog-breeds/$1</url>
    <selector>
        <type>CLASS_NAME</type>
        <value>geekitem_infotable</value>
        <selector>
            <type>XPATH</type>
            <value>//td[@width=150]</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[@width=150]/following-sibling::td[1]</value>
        </selector>
    </selector>
</tns:DCSpec>

=== jmthompson2015/rivalry/trunk/example/src/main/resources/org/rivalry/example/bestplace/DataCollectorBestPlaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector http://rivalry.googlecode.com/svn/trunk/core/src/main/resources/DataCollector.xsd">
    <url>http://www.bestplaces.net/city/$1</url>
    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Climate']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgClimate</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a|//td/font/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>(//td/a|//td/font/a)/ancestor::td/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Climate</value>
        </selector>
    </selector>
    
    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>XPATH</type>
            <value>//a[text()='Crime']</value>
        </selector>
    </selector>
    <selector>
        <type>ID</type>
        <value>mainContent_dgCrime</value>
        <selector>
            <type>XPATH</type>
            <value>//td/a</value>
        </selector>
        <selector>
            <type>XPATH</type>
            <value>//td[a]/following-sibling::td[1]</value>
        </selector>
        <selector>
            <type>LITERAL</type>
            <value>Crime</value>
        </selector>
    </selector>
</tns:DCSpec>

=== jmthompson2015/rivalry/trunk/core/src/test/resources/org/rivalry/core/datacollector/io/DataCollectorYahooFinance.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector file:////Users/jmthompson/Dropbox/SoftwareDev/JavaProjects/rivalry/trunk/core/src/main/resources/DataCollector.xsd"
    >
    <!-- 
    xsi:schemaLocation="http://core.rivalry.org/datacollector file:///../../../../../../../main/resources/DataCollector.xsd"
     -->
    <url>http://finance.yahoo.com/q/ks?s=$1+Key+Statistics</url>
    <selector>
        <type>CLASS_NAME</type>
        <value>yfnc_datamodoutline1</value>
        <selector>
            <type>CLASS_NAME</type>
            <value>yfnc_tablehead1</value>
        </selector>
        <selector>
            <type>CLASS_NAME</type>
            <value>yfnc_tabledata1</value>
        </selector>
    </selector>
</tns:DCSpec>

=== jmthompson2015/rivalry/core/src/test/resources/org/rivalry/core/datacollector/DataCollectorIllyriadEconomy.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DCSpec xmlns:tns="http://core.rivalry.org/datacollector"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/datacollector file:////Users/jmthompson/Dropbox/SoftwareDev/JavaProjects/rivalry/trunk/core/src/main/resources/DataCollector.xsd">
    <url></url>
    <selector>
        <type>CLICK</type>
        <value></value>
        <selector>
            <type>LINK_TEXT</type>
            <value>#/Trade/Markets</value>
        </selector>
    </selector>
</tns:DCSpec>
