=== jmthompson2015/rivalry/core/src/main/resources/RivalryData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1"
    xmlns:inheritance="http://jaxb2-commons.dev.java.net/basic/inheritance"
    jaxb:extensionBindingPrefixes="inheritance">

    <xs:annotation>
        <xs:appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="org.rivalry.core.model" />
            </jaxb:schemaBindings>
        </xs:appinfo>
    </xs:annotation>

    <xs:complexType name="DefaultEntity">
        <xs:annotation>
            <xs:appinfo>
                <jaxb:class>
                    <jaxb:javadoc>
                        Provides an entity for a decision
                        making application.
                    </jaxb:javadoc>
                </jaxb:class>
                <inheritance:implements>org.rivalry.core.model.Entity
                </inheritance:implements>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="description" type="xs:string"
                minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DefaultCategory">
        <xs:annotation>
            <xs:appinfo>
                <jaxb:class>
                    <jaxb:javadoc>
                        Provides a category for a decision
                        making application.
                    </jaxb:javadoc>
                </jaxb:class>
                <inheritance:extends>org.rivalry.core.model.DefaultEntity
                </inheritance:extends>
                <inheritance:implements>org.rivalry.core.model.Category
                </inheritance:implements>
            </xs:appinfo>
        </xs:annotation>
    </xs:complexType>

    <xs:complexType name="DefaultCriterion">
        <xs:annotation>
            <xs:appinfo>
                <jaxb:class>
                    <jaxb:javadoc>
                        Provides a criterion for a decision
                        making application.
                    </jaxb:javadoc>
                </jaxb:class>
                <inheritance:extends>org.rivalry.core.model.DefaultEntity
                </inheritance:extends>
                <inheritance:implements>org.rivalry.core.model.Criterion
                </inheritance:implements>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="category" type="DefaultCategory">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:property>
                            <jaxb:baseType
                                name="org.rivalry.core.model.Category" />
                        </jaxb:property>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
            <xs:choice>
                <xs:element name="autoMinMax" type="xs:boolean"
                    default="false" />
                <xs:sequence>
                    <xs:element name="minimumRating" type="xs:double" />
                    <xs:element name="maximumRating" type="xs:double" />
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DefaultCandidate">
        <xs:annotation>
            <xs:appinfo>
                <jaxb:class>
                    <jaxb:javadoc>
                        Provides a candidate for a decision
                        making application.
                    </jaxb:javadoc>
                </jaxb:class>
                <inheritance:extends>org.rivalry.core.model.AbstractCandidate
                </inheritance:extends>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="page" type="xs:string" />
            <xs:element name="values" type="CriterionMapModeller">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:property>
                            <jaxb:baseType
                                name="org.rivalry.core.model.CriterionMap" />
                        </jaxb:property>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CriterionMapModeller">
        <xs:sequence>
            <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="key" type="xs:string"/>
                        <xs:element name="value" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="DefaultRivalryData">
        <xs:annotation>
            <xs:appinfo>
                <jaxb:class>
                    <jaxb:javadoc>Provides a data bean for a decision
                        making
                        application.
                    </jaxb:javadoc>
                </jaxb:class>
                <inheritance:extends>org.rivalry.core.model.AbstractRivalryData
                </inheritance:extends>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="createDate" type="xs:dateTime">
                    <xs:annotation>
                        <xs:appinfo>
                            <jaxb:property>
                                <jaxb:baseType>
                                    <jaxb:javaType name="java.util.Calendar"
                                        parseMethod="javax.xml.bind.DatatypeConverter.parseDateTime"
                                        printMethod="javax.xml.bind.DatatypeConverter.printDateTime" />
                                </jaxb:baseType>
                            </jaxb:property>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="description" type="xs:string" />
                <xs:element name="preferencePrefix" type="xs:string" />
                <xs:element name="category" type="DefaultCategory"
                    minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:appinfo>
                            <jaxb:property name="categories">
                                <jaxb:baseType
                                    name="org.rivalry.core.model.Category" />
                            </jaxb:property>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="criterion" type="DefaultCriterion"
                    maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:appinfo>
                            <jaxb:property name="criteria">
                                <jaxb:baseType
                                    name="org.rivalry.core.model.Criterion" />
                            </jaxb:property>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
                <xs:element name="candidate" type="DefaultCandidate"
                    maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:appinfo>
                            <jaxb:property name="candidates">
                                <jaxb:baseType
                                    name="org.rivalry.core.model.Candidate" />
                            </jaxb:property>
                        </xs:appinfo>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jmthompson2015/rivalry/trunk/core/src/test/resources/MacintoshComputersRivalryData.xml
<?xml version="1.0" encoding="UTF-8"?>
<DefaultRivalryData xmlns:tns="http://core.rivalry.org/model"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://core.rivalry.org/model file:////Users/jmthompson/Dropbox/SoftwareDev/JavaProjects/rivalry/core/src/main/resources/RivalryData.xsd">
    <createDate>2015-03-02T12:58:00</createDate>
    <description>Macintosh Computers rivalry data</description>
    <preferencePrefix>macComputers</preferencePrefix>
    <criterion>
        <name>release</name>
        <description>Release</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>processorSpeed</name>
        <description>Processor Speed (GHz)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>processor</name>
        <description>Processor</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>ram</name>
        <description>RAM (GB)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>harddrive</name>
        <description>Harddrive (GB)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>harddriveSpeed</name>
        <description>Harddrive Speed (rpm)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>flashStorage</name>
        <description>Flash Storage (GB)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>graphicsCard</name>
        <description>Graphics Card</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>graphicsRam</name>
        <description>Graphics RAM (MB)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>price</name>
        <description>Price ($)</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <criterion>
        <name>geekbench3Score</name>
        <description>Geekbench 3 Score</description>
        <autoMinMax>true</autoMinMax>
    </criterion>
    <candidate>
        <name>Mac Mini Late 2014 1.4 GHz</name>
        <page>http://store.apple.com/us/buy-mac/mac-mini</page>
        <values>
            <entry>
                <key>release</key>
                <value>2014/10</value>
            </entry>
            <entry>
                <key>processorSpeed</key>
                <value>1.4</value>
            </entry>
            <entry>
                <key>processor</key>
                <value>dual-core Intel Core i5</value>
            </entry>
            <entry>
                <key>ram</key>
                <value>4</value>
            </entry>
            <entry>
                <key>harddrive</key>
                <value>500</value>
            </entry>
            <entry>
                <key>harddriveSpeed</key>
                <value>5400</value>
            </entry>
            <entry>
                <key>graphicsCard</key>
                <value>Intel HD Graphics 5000</value>
            </entry>
            <entry>
                <key>graphicsRam</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>price</key>
                <value>499</value>
            </entry>
            <entry>
                <key>geekbench3Score</key>
                <value>5382</value>
            </entry>
        </values>
    </candidate>
    <candidate>
        <name>Mac Mini Late 2014 2.6 GHz</name>
        <page>http://store.apple.com/us/buy-mac/mac-mini</page>
        <values>
            <entry>
                <key>release</key>
                <value>2014/10</value>
            </entry>
            <entry>
                <key>processorSpeed</key>
                <value>2.6</value>
            </entry>
            <entry>
                <key>processor</key>
                <value>dual-core Intel Core i5</value>
            </entry>
            <entry>
                <key>ram</key>
                <value>8</value>
            </entry>
            <entry>
                <key>harddrive</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>harddriveSpeed</key>
                <value>5400</value>
            </entry>
            <entry>
                <key>graphicsCard</key>
                <value>Intel Iris Graphics</value>
            </entry>
            <entry>
                <key>graphicsRam</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>price</key>
                <value>699</value>
            </entry>
            <entry>
                <key>geekbench3Score</key>
                <value>6581</value>
            </entry>
        </values>
    </candidate>
    <candidate>
        <name>Mac Mini Late 2014 2.8 GHz</name>
        <page>http://store.apple.com/us/buy-mac/mac-mini</page>
        <values>
            <entry>
                <key>release</key>
                <value>2014/10</value>
            </entry>
            <entry>
                <key>processorSpeed</key>
                <value>2.6</value>
            </entry>
            <entry>
                <key>processor</key>
                <value>dual-core Intel Core i5</value>
            </entry>
            <entry>
                <key>ram</key>
                <value>8</value>
            </entry>
            <entry>
                <key>harddrive</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>harddriveSpeed</key>
                <value>Fusion</value>
            </entry>
            <entry>
                <key>flashStorage</key>
                <value>Fusion</value>
            </entry>
            <entry>
                <key>graphicsCard</key>
                <value>Intel Iris Graphics</value>
            </entry>
            <entry>
                <key>graphicsRam</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>price</key>
                <value>999</value>
            </entry>
            <entry>
                <key>geekbench3Score</key>
                <value>7057</value>
            </entry>
        </values>
    </candidate>
    <candidate>
        <name>iMac 27-inch Late 2013 3.2 GHz</name>
        <page>http://store.apple.com/us/buy-mac/imac</page>
        <values>
            <entry>
                <key>release</key>
                <value>2013/09</value>
            </entry>
            <entry>
                <key>processorSpeed</key>
                <value>3.2</value>
            </entry>
            <entry>
                <key>processor</key>
                <value>quad-core Intel Core i5</value>
            </entry>
            <entry>
                <key>ram</key>
                <value>8</value>
            </entry>
            <entry>
                <key>harddrive</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>harddriveSpeed</key>
                <value>7200</value>
            </entry>
            <entry>
                <key>graphicsCard</key>
                <value>NVIDIA GeForce GT 755M</value>
            </entry>
            <entry>
                <key>graphicsRam</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>price</key>
                <value>1799</value>
            </entry>
            <entry>
                <key>geekbench3Score</key>
                <value>11271</value>
            </entry>
        </values>
    </candidate>
    <candidate>
        <name>iMac 27-inch Late 2013 3.4 GHz</name>
        <page>http://store.apple.com/us/buy-mac/imac</page>
        <values>
            <entry>
                <key>release</key>
                <value>2013/09</value>
            </entry>
            <entry>
                <key>processorSpeed</key>
                <value>3.4</value>
            </entry>
            <entry>
                <key>processor</key>
                <value>quad-core Intel Core i5</value>
            </entry>
            <entry>
                <key>ram</key>
                <value>8</value>
            </entry>
            <entry>
                <key>harddrive</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>harddriveSpeed</key>
                <value>7200</value>
            </entry>
            <entry>
                <key>graphicsCard</key>
                <value>NVIDIA GeForce GT 775M</value>
            </entry>
            <entry>
                <key>graphicsRam</key>
                <value>2048</value>
            </entry>
            <entry>
                <key>price</key>
                <value>1999</value>
            </entry>
            <entry>
                <key>geekbench3Score</key>
                <value>11796</value>
            </entry>
        </values>
    </candidate>
    <candidate>
        <name>iMac 27-inch Retina 5K Late 2014 3.5 GHz</name>
        <page>http://store.apple.com/us/buy-mac/imac</page>
        <values>
            <entry>
                <key>release</key>
                <value>2014/10</value>
            </entry>
            <entry>
                <key>processorSpeed</key>
                <value>3.5</value>
            </entry>
            <entry>
                <key>processor</key>
                <value>quad-core Intel Core i5</value>
            </entry>
            <entry>
                <key>ram</key>
                <value>8</value>
            </entry>
            <entry>
                <key>harddrive</key>
                <value>1024</value>
            </entry>
            <entry>
                <key>harddriveSpeed</key>
                <value>Fusion</value>
            </entry>
            <entry>
